allow -F to modify framework version for non-XNA/after setup

diff --git a/fnaify b/fnaify
--- a/fnaify
+++ b/fnaify
@@ -1092,19 +1092,30 @@ xnasetup()
 
 get_frameworkfile()
 {
-	if [ -e "$gamedir/FNA.dll" ]; then
-		frameworkfile="FNA.dll"
-	elif [ -e "$gamedir/MonoGame.Framework.dll" ]; then
-		frameworkfile="MonoGame.Framework.dll"
+	if [ -z "$frameworkfile" ] ; then
+		if [ -e "$gamedir/FNA.dll" ]; then
+			frameworkfile="$gamedir/FNA.dll"
+		elif [ -e "$gamedir/MonoGame.Framework.dll" ]; then
+			frameworkfile="$gamedir/MonoGame.Framework.dll"
+		fi
 	fi
 }
 
 get_frameworkversion()
 {
 	[ -z "$frameworkfile" ] && return	# either no framework file, or need to run get_frameworkfile() first
-	frameworkversion="$(monodis --assembly "$frameworkfile" | fgrep Version | sed -E 's/Version:[[:blank:]]*//')"
-	frameworkmajor=`echo "$frameworkversion" | sed -n -E "s/([0-9]+)\.[0-9]+\.[0-9]+\.[0-9]+/\1/p"`
-	frameworkminor=`echo "$frameworkversion" | sed -n -E "s/[0-9]+\.([0-9]+)\.[0-9]+\.[0-9]+/\1/p"`
+	echo "$(monodis --assembly "$frameworkfile" | fgrep Version | sed -E 's/Version:[[:blank:]]*//')"
+}
+
+get_frameworkmajor()
+{
+	echo "$1" | sed -n -E "s/([0-9]+)\.[0-9\.]+/\1/p"
+}
+
+get_frameworkminor()
+{
+	# strip leading zeros
+	echo "$1" | sed -n -E "s/[0-9]+\.([0-9]+).*/\1/p" | sed "s/^0*//"
 }
 
 check_eagle_island()
@@ -1115,16 +1126,6 @@ check_eagle_island()
 		debug_echo "correct gamedir for Eagle Island"
 		gamedir="${gamedir}/Linux"
 	}
-}
-
-###################################
-### MODES: help, run, setup	###
-###################################
-
-help()
-{
-	echo "$USAGE"
-	exit 0
 }
 
 run()
@@ -1175,8 +1176,8 @@ run()
 		[ -e "$f" ] && { \
 			debug_echo "existing symlink target: ${f}.config -> $(readlink "${f}.config")"
 			gameconfigsymlink="${gameconfigsymlink}${f}.config "
-			[ "x$gameconfig" = "x$(readlink "${f}.config")" ] || \
-				ln -sf "$gameconfig" "${f}.config"
+			[ "x$gameconfig" = "x$(readlink "${f}.config")" ] \
+				|| ln -sf "$gameconfig" "${f}.config"
 		}
 	done
 	gameconfigsymlink="${gameconfigsymlink}${my_exe}.config "
@@ -1187,7 +1188,25 @@ run()
 	depdir="$(echo "$depdir" | sed -E 's/:$//')"
 	monopath="$(echo "$monopath" | sed -E 's/:$//' | sed -E 's/^://')"
 	get_frameworkfile
-	get_frameworkversion
+
+	# check if framework needs to be updated
+	file_fwv="$(get_frameworkversion)"	# the version of the framework in the framework file
+	if [ -z "$frameworkversion" ] ; then
+		frameworkversion="$file_fwv"
+	elif [ "$(get_frameworkmajor "$file_fwv").$(get_frameworkminor "$file_fwv")" != "$(get_frameworkmajor "$frameworkversion").$(get_frameworkminor "$frameworkversion")" ] ; then
+		[ "$(dirname "$frameworkfile")" != "$gamedir" ] && { \
+			echo "Error: can't set framework version AND specify framework file outside game dir."
+			exit 1
+		}
+		install_fna $frameworkversion
+		# assert framework version is now correct; re-read file_fwv
+		file_fwv="$(get_frameworkversion)"
+		[ "$(get_frameworkmajor "$file_fwv").$(get_frameworkminor "$file_fwv")" == "$(get_frameworkmajor "$frameworkversion").$(get_frameworkminor "$frameworkversion")" ] || { \
+			echo "Error installing the requested framework version."
+			exit 1
+		}
+	fi
+
 	datasize=$(( $(ulimit -d) / 1024 ))
 
 	echo
@@ -1246,7 +1265,12 @@ setup()
 	debug_echo "Setting up the framework files"
 	get_frameworkfile
 	debug_echo "	framework file:			$frameworkfile"
-	get_frameworkversion
+	if [ -z "$frameworkversion" ] ; then
+		frameworkversion="$(get_frameworkversion)"
+	fi
+	frameworkmajor="$(get_frameworkmajor $frameworkversion)"
+	frameworkminor="$(get_frameworkminor $frameworkversion)"
+
 	debug_echo "	framework version:	$frameworkversion"
 
 	if [ -z "$frameworkfile" ] ; then
