add configbasearray for assemblies that need a .config; add datasize (ulimit) to fnaify runtime information; readd LoadLibrary dllmap

diff --git a/fnaify b/fnaify
--- a/fnaify
+++ b/fnaify
@@ -81,6 +81,15 @@ monopath="${MONO_PATH}"
 netstub_commit=e7d890e0ede0caa9e76ef37af6070344e3ab0abf
 newline='
 '
+SAVEIFS=$IFS
+exefile=
+nexefile=0	# TODO: is nexefile really needed?
+my_exe=""
+exe_flags=""
+exe_env=""
+fna_warning=0
+nlog_warning=0
+needlibarray="" # array that will hold the names of needed libraries
 
 if [ -d "/usr/local/lib/steamworks-nosteam" ] ; then
 	monopath="${monopath}:/usr/local/lib/steamworks-nosteam"
@@ -92,19 +101,6 @@ fi
 if [ -d "/usr/local/share/fnaify-libs" ]; then
 	depdir="/usr/local/share/fnaify-libs:$depdir"
 fi
-
-#list of exefiles and their number
-exefile=
-nexefile=0	# TODO: is nexefile really needed?
-my_exe=""
-exe_flags=""
-exe_env=""
-
-SAVEIFS=$IFS
-fna_warning=0
-nlog_warning=0
-
-needlibarray="" # array that will hold the names of needed libraries
 
 # array of lib names to ignore for the configuration checking
 ignoredarray="
@@ -165,6 +161,13 @@ libMonoPosixHelper.so.x86_64
 monoconfig
 monomachineconfig
 mscorlib.dll
+"
+
+configbasearray="
+FNA.dll
+MonoGame.Framework.dll
+Nuclex.Input.dll
+OpenAL-CS.dll
 "
 
 debug_echo()
@@ -379,9 +382,6 @@ check_gameconfig()
 
 	<!-- Atom Zombie Smasher -->
 	<dllmap dll="msvcr100.dll" target="libc.so"/>
-
-	<!-- Terraria, Solaroids -->
-	<dllmap dll="gdiplus.dll" target="libgdiplus.so"/>
 
 	<!-- Nuclex.Input: Dead Pixels, Amazing Princess Sarah, Akane the Kunoichi -->
 	<dllmap dll="kernel32">
@@ -965,22 +965,29 @@ run()
 		ScourgeBringer.exe)			exe_flags="${exe_flags}-noSound "		;;
 	esac
 	my_exe="$(echo "$my_exe" | tr -d '\:')"
+	gameconfigsymlink="${gameconfigsymlink}${my_exe}.config "
+	[ "x$gameconfig" = "x$(readlink "${my_exe}.config")" ] || \
+		ln -sf "$gameconfig" "${my_exe}.config"
+
+	# Config
+	check_gameconfig
+	[ -e $gameconfig ] || { echo "ERROR: provided gameconfig file not existent: $gameconfig"; exit 1; }
+	debug_echo "gameconfig: $gameconfig"
+	for f in $configbasearray; do
+		debug_echo "existing symlink target: ${f}.config -> $(readlink "${f}.config")"
+		[ -e "$f" ] && { \
+			gameconfigsymlink="${gameconfigsymlink}${f}.config "
+			[ "x$gameconfig" = "x$(readlink "${f}.config")" ] || \
+				ln -sf "$gameconfig" "${f}.config"
+		}
+	done
 
 	# format all relevant command variables
 	depdir="$(echo "$depdir" | sed -E 's/:$//')"
 	monopath="$(echo "$monopath" | sed -E 's/:$//' | sed -E 's/^://')"
 	get_frameworkfile
 	get_frameworkversion
-	[ -n "$frameworkfile" ] \
-		&& gameconfigsymlink="${frameworkfile}.config" \
-		|| gameconfigsymlink="${my_exe}.config"
-	check_gameconfig
-	[ -e $gameconfig ] || { echo "ERROR: provided gameconfig file not existant: $gameconfig"; exit 1; }
-	debug_echo "gameconfig: $gameconfig"
-	echo "existing symlink target: $gameconfigsymlink -> $(readlink "$gameconfigsymlink")"
-	[ "x$gameconfig" = "x$(readlink "$gameconfigsymlink")" ] \
-		&& debug_echo "existing symlink ok" \
-		|| ln -sf "$gameconfig" "$gameconfigsymlink"
+	datasize=$(( $(ulimit -d) / 1024 ))
 
 	echo
 	printdash "fnaify runtime configuration"
@@ -990,14 +997,16 @@ run()
 	echo "Native Library Directories:	$depdir"
 	echo "Framework File:			$frameworkfile"
 	echo "Framework File Version:		$frameworkversion"
-	echo "Symlink to Config:		$gameconfigsymlink"
+	echo "Symlinks to Config:		$gameconfigsymlink"
 	echo "Config File:			$gameconfig"
 	echo "Other Runtime Environment:	$exe_env"
 	echo "Runtime Flags:			$exe_flags"
+	echo "Datasize Limit:			${datasize}M"
 
-	echo -n "\nNOTE: if game should unexpectedly fail to start, make sure datasize limit is high enough. "
-	echo "AT LEAST 2G are recommended for most games. See ksh(1) for ulimit command documentation"
-	echo
+	[ $datasize -lt 2048 ] && { \
+		echo "AT LEAST 2G are recommended for most games. See ksh(1) for ulimit command documentation"
+		echo
+	}
 
 	# check if broken symlinks exist in the game directory, e.g. libdl.so.2
 	for l in $(find . -type l); do
